# Generated by Django 2.2 on 2019-04-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190420_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='simuser',
            name='email',
            field=models.EmailField(default='default@notasite.com', max_length=254),
            preserve_default=False,
        ),
    ]
