# Generated by Django 2.2 on 2019-04-20 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_simuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
