# Generated by Django 2.2 on 2019-04-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_simuser_lfg'),
    ]

    operations = [
        migrations.AddField(
            model_name='simuser',
            name='losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='simuser',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
